version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://backend:8081

  backend:
    # This should be replaced with your actual backend Docker configuration
    # The following is just a placeholder
    image: ${BACKEND_IMAGE:-backend:latest}
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Add other environment variables as needed

networks:
  app-network:
    driver: bridge